-- FR-35.1: goal synergy links — a user records how one goal leverages or
-- advances another, with a note. Informational only (BR-29): no effect on
-- progress, status, or archival.
--
-- The FKs cascade on goal delete, so a link never outlives either of its goals.
-- A self-link is rejected by CHECK. Unordered-pair uniqueness is enforced by a
-- plain composite UNIQUE plus a service-side normalisation rule that always
-- stores the lower goal id in goal_id and the higher in related_goal_id — so
-- (A,B) and (B,A) map to the same row and can't be linked twice. (A functional
-- LEAST/GREATEST index would do this in one place, but H2 — the test database —
-- doesn't support expression indexes, so the ordering lives in the service.)
CREATE TABLE goal_synergy_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(id),
    goal_id BIGINT NOT NULL REFERENCES goals(id) ON DELETE CASCADE,
    related_goal_id BIGINT NOT NULL REFERENCES goals(id) ON DELETE CASCADE,
    note VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_goal_synergy_distinct CHECK (goal_id <> related_goal_id),
    CONSTRAINT uk_goal_synergy_pair UNIQUE (user_id, goal_id, related_goal_id)
);
