-- FR-38: in-app issue & improvement reporting. A user raises a bug or
-- improvement from inside the app; an ADMIN triages the queue. Additive — no
-- changes to existing tables, and no scheduler/notification infrastructure
-- (notifying the user of a resolution is out of scope, FR-38.5).
--
-- severity is nullable: it is required only when report_type = 'BUG' (BR-32),
-- enforced in the service alongside the "resolved bug needs a resolution note"
-- rule. context_route and app_version are captured automatically on submit.
CREATE TABLE issue_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES app_users(id),
    report_type VARCHAR(40) NOT NULL,
    title VARCHAR(220) NOT NULL,
    description VARCHAR(3000),
    severity VARCHAR(40),
    context_route VARCHAR(300),
    app_version VARCHAR(40),
    status VARCHAR(40) NOT NULL,
    resolution_note VARCHAR(3000),
    archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_issue_reports_user_code UNIQUE (user_id, code)
);

-- Admin triage lists by status; the owner lists their own reports.
CREATE INDEX idx_issue_reports_status ON issue_reports (status);
CREATE INDEX idx_issue_reports_user ON issue_reports (user_id);
