-- Password recovery by email: a signed-out user proves control of their inbox
-- and sets a new password without knowing the old one.
--
-- The token itself is never stored. token_hash holds a SHA-256 of the value
-- that was emailed, so read access to this table does not let anyone reset an
-- account — the same reasoning that keeps passwords out of app_users. Lookup is
-- therefore by hash, which is what the unique index is for.
--
-- used_at is nullable and set on redemption rather than deleting the row: a
-- token that has already been spent must be distinguishable from one that never
-- existed, so a replayed link can be refused rather than silently treated as
-- unknown. Rows are pruned by age, not on use.
CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(id),
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_password_reset_tokens_hash UNIQUE (token_hash)
);

-- Redeeming a link looks the token up by hash; issuing one invalidates whatever
-- the same user still has outstanding.
CREATE INDEX idx_password_reset_tokens_user ON password_reset_tokens (user_id);
