-- FR-59.1: a lightweight, user-authored gratitude log — a new table, not
-- an extension of an existing one, since entries aren't tied to any single
-- Review or Obstacle record.
CREATE TABLE gratitude_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(id),
    category VARCHAR(20) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    related_dream_id BIGINT REFERENCES dreams(id),
    related_goal_id BIGINT REFERENCES goals(id),
    archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_gratitude_entries_user ON gratitude_entries (user_id);
